from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..models.doktyp import Doktyp
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.autor import Autor
    from ..models.touched_by_item import TouchedByItem


T = TypeVar("T", bound="Dokument")


@_attrs_define
class Dokument:
    r"""Ein Dokument. Kann z.B. ein Protokoll, eine Drucksache oder eine Stellungnahme sein. Man beachte, dass für
    verschiedene Typen verschiedene Felder nur formal optional sind. So ist zum Beispiel für jede Stellungnahme eine
    Meinung gefragt und für jeden Gesetzesentwurf ein Vorwort. Da Dokumente relativ große Objekte werden können (O(kB)),
    wird überall wo sie Teilobjekte sind (bei Stationen und Sitzungen) nur die UUID vom Server returned, und das
    Dokument muss in einem zweiten Request geladen werden.

        Example:
            {'api_id': 'a1b2c3d4-e5f6-7890-abcd-1234567890ab', 'typ': 'entwurf', 'titel': 'Entwurf eines Gesetzes zur
                Änderung des Bundeswahlgesetzes', 'kurztitel': 'Änderung des Bundeswahlgesetzes', 'vorwort': 'Mit dem
                vorliegenden Entwurf soll das Bundeswahlgesetz an die aktuellen Anforderungen angepasst werden.', 'volltext':
                'Der Bundestag hat mit Zustimmung des Bundesrates das folgende Gesetz beschlossen:\n\nArtikel 1\nÄnderung des
                Bundeswahlgesetzes\n\nDas Bundeswahlgesetz in der Fassung der Bekanntmachung vom 23. Juli 1993 (BGBl. I S. 1288,
                1594) wird wie folgt geändert:\n\n1. § 1 Absatz 1 wird wie folgt gefasst: [...]', 'zusammenfassung': 'Änderung
                des Bundeswahlgesetzes zur Anpassung an aktuelle Anforderungen.', 'zp_modifiziert': '2024-03-15T14:30:00+01:00',
                'zp_referenz': '2024-03-01T00:00:00+01:00', 'zp_erstellt': '2024-03-10T09:15:00+01:00', 'link':
                'https://dip.bundestag.de/dokument/12345', 'hash': 'a1b2c3d4e5f6g7h8i9j0', 'meinung': 4, 'schlagworte':
                ['wahlrecht', 'bundestagswahl', 'reform'], 'autoren': [{'person': 'Dr. Maria Schmidt', 'organisation':
                'Bundesministerium des Innern', 'fachgebiet': 'Wahlrecht'}], 'drucksnr': 'BT-Drs. 20/12345'}

        Attributes:
            typ (Doktyp): Typ eines Dokuments. Beschreibt explizit nicht den Kontext, sondern nur den Typ des Inhalts. (z.B.
                'tops' kann sowohl für Plenarsitzungen als auch für Ausschusssitzungen relevant sein)
            titel (str): Offizieller Titel
            volltext (str): Volltext des Dokuments
            zp_modifiziert (datetime.datetime): Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert am
                9.3. Example: 2024-03-09T00:00:00+00:00.
            zp_referenz (datetime.datetime): Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert am 9.3.
                Example: 2024-03-07T00:00:00+00:00.
            link (str):
            hash_ (str):
            autoren (list[Autor]): Liste von Autoren des Dokuments. Kann z.B. eine Person, eine Organisation oder ein
                Gremium sein.
            api_id (UUID | Unset): optional, here for future references. Is generated by the server.
            touched_by (list[TouchedByItem] | Unset): list of scraper uuids / key database ids that have touched this object
            drucksnr (str | Unset):
            kurztitel (str | Unset): Griffigerer Titel für besseres Verständnis
            vorwort (str | Unset): Präambel, Vorwort oder Intentionsbeschreibung. Wird für Ähnlichkeitsanalysen von
                Gesetzestexten genutzt
            zusammenfassung (str | Unset):
            zp_erstellt (datetime.datetime | Unset): Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert
                am 9.3. Example: 2024-03-08T00:00:00+00:00.
            meinung (int | Unset): Meinungsbild des Dokuments bei Stln / Beschlempf: 1=schlecht, 5=gut bzw. 1=ablehnung
                empf.,2-4=zust in geänderter Fassung, 5=zustimmung empf.
            schlagworte (list[str] | Unset):
    """

    typ: Doktyp
    titel: str
    volltext: str
    zp_modifiziert: datetime.datetime
    zp_referenz: datetime.datetime
    link: str
    hash_: str
    autoren: list[Autor]
    api_id: UUID | Unset = UNSET
    touched_by: list[TouchedByItem] | Unset = UNSET
    drucksnr: str | Unset = UNSET
    kurztitel: str | Unset = UNSET
    vorwort: str | Unset = UNSET
    zusammenfassung: str | Unset = UNSET
    zp_erstellt: datetime.datetime | Unset = UNSET
    meinung: int | Unset = UNSET
    schlagworte: list[str] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        typ = self.typ.value

        titel = self.titel

        volltext = self.volltext

        zp_modifiziert = self.zp_modifiziert.isoformat()

        zp_referenz = self.zp_referenz.isoformat()

        link = self.link

        hash_ = self.hash_

        autoren = []
        for autoren_item_data in self.autoren:
            autoren_item = autoren_item_data.to_dict()
            autoren.append(autoren_item)

        api_id: str | Unset = UNSET
        if not isinstance(self.api_id, Unset):
            api_id = str(self.api_id)

        touched_by: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.touched_by, Unset):
            touched_by = []
            for componentsschemastouched_by_item_data in self.touched_by:
                componentsschemastouched_by_item = componentsschemastouched_by_item_data.to_dict()
                touched_by.append(componentsschemastouched_by_item)

        drucksnr = self.drucksnr

        kurztitel = self.kurztitel

        vorwort = self.vorwort

        zusammenfassung = self.zusammenfassung

        zp_erstellt: str | Unset = UNSET
        if not isinstance(self.zp_erstellt, Unset):
            zp_erstellt = self.zp_erstellt.isoformat()

        meinung = self.meinung

        schlagworte: list[str] | Unset = UNSET
        if not isinstance(self.schlagworte, Unset):
            schlagworte = self.schlagworte

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "typ": typ,
                "titel": titel,
                "volltext": volltext,
                "zp_modifiziert": zp_modifiziert,
                "zp_referenz": zp_referenz,
                "link": link,
                "hash": hash_,
                "autoren": autoren,
            }
        )
        if api_id is not UNSET:
            field_dict["api_id"] = api_id
        if touched_by is not UNSET:
            field_dict["touched_by"] = touched_by
        if drucksnr is not UNSET:
            field_dict["drucksnr"] = drucksnr
        if kurztitel is not UNSET:
            field_dict["kurztitel"] = kurztitel
        if vorwort is not UNSET:
            field_dict["vorwort"] = vorwort
        if zusammenfassung is not UNSET:
            field_dict["zusammenfassung"] = zusammenfassung
        if zp_erstellt is not UNSET:
            field_dict["zp_erstellt"] = zp_erstellt
        if meinung is not UNSET:
            field_dict["meinung"] = meinung
        if schlagworte is not UNSET:
            field_dict["schlagworte"] = schlagworte

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.autor import Autor
        from ..models.touched_by_item import TouchedByItem

        d = dict(src_dict)
        typ = Doktyp(d.pop("typ"))

        titel = d.pop("titel")

        volltext = d.pop("volltext")

        zp_modifiziert = isoparse(d.pop("zp_modifiziert"))

        zp_referenz = isoparse(d.pop("zp_referenz"))

        link = d.pop("link")

        hash_ = d.pop("hash")

        autoren = []
        _autoren = d.pop("autoren")
        for autoren_item_data in _autoren:
            autoren_item = Autor.from_dict(autoren_item_data)

            autoren.append(autoren_item)

        _api_id = d.pop("api_id", UNSET)
        api_id: UUID | Unset
        if isinstance(_api_id, Unset):
            api_id = UNSET
        else:
            api_id = UUID(_api_id)

        _touched_by = d.pop("touched_by", UNSET)
        touched_by: list[TouchedByItem] | Unset = UNSET
        if _touched_by is not UNSET:
            touched_by = []
            for componentsschemastouched_by_item_data in _touched_by:
                componentsschemastouched_by_item = TouchedByItem.from_dict(componentsschemastouched_by_item_data)

                touched_by.append(componentsschemastouched_by_item)

        drucksnr = d.pop("drucksnr", UNSET)

        kurztitel = d.pop("kurztitel", UNSET)

        vorwort = d.pop("vorwort", UNSET)

        zusammenfassung = d.pop("zusammenfassung", UNSET)

        _zp_erstellt = d.pop("zp_erstellt", UNSET)
        zp_erstellt: datetime.datetime | Unset
        if isinstance(_zp_erstellt, Unset):
            zp_erstellt = UNSET
        else:
            zp_erstellt = isoparse(_zp_erstellt)

        meinung = d.pop("meinung", UNSET)

        schlagworte = cast(list[str], d.pop("schlagworte", UNSET))

        dokument = cls(
            typ=typ,
            titel=titel,
            volltext=volltext,
            zp_modifiziert=zp_modifiziert,
            zp_referenz=zp_referenz,
            link=link,
            hash_=hash_,
            autoren=autoren,
            api_id=api_id,
            touched_by=touched_by,
            drucksnr=drucksnr,
            kurztitel=kurztitel,
            vorwort=vorwort,
            zusammenfassung=zusammenfassung,
            zp_erstellt=zp_erstellt,
            meinung=meinung,
            schlagworte=schlagworte,
        )

        dokument.additional_properties = d
        return dokument

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
