repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=1000']
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-toml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: name-tests-test
    args: ['--pytest-test-first']
    exclude: tests/unit/pazufa_scraper_be/helpers\.py
  - id: check-yaml
  - id: debug-statements
- repo: local
  hooks:
  - id: ruff-check
    name: linting
    entry: uv run ruff check
    pass_filenames: false
    language: system
    types_or: [python, pyi]
  - id: ruff-format
    name: formatting
    entry: uv run ruff format
    pass_filenames: false
    language: system
    types_or: [python, pyi]
  - id: ty
    name: type check
    entry: uv run ty check pazufa_scraper_be/ tests/
    pass_filenames: false
    language: system
    types_or: [python, pyi]
  - id: test
    name: test
    entry: uv run pytest tests/unit
    pass_filenames: false
    require_serial: true
    language: system
    types_or: [python, pyi]
