DOK_BASE_URL = "https://pardok.parlament-berlin.de/starweb/adis/citat/VT"

DOKUMENT_FILE_NAME = "DOKUMENT.pdf"
URL_FILE_NAME = "URL.txt"
DOWNLOAD_TIME_FILE_NAME = "DOWNLOAD_TIME.txt"
LAST_MODIFIED_FILE_NAME = "LAST_MODIFIED.txt"
FILE_BYTE_HASH_FILE_NAME = "FILE_BYTE_HASH.txt"
TEXT_FILE_NAME = "TEXT.txt"
SUMMARY_FILE_NAME = "SUMMARY.txt"

BESCHLUSSPROTOKOLL_ABBR = "bp"
INHALTSPROTOKOLL_ABBR = "ip"
WORTPROTOKOLL_ABBR = "wp"
