from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.doktyp import Doktyp
from ..types import UNSET, Unset
from dateutil.parser import isoparse
from typing import cast
from uuid import UUID
import datetime

if TYPE_CHECKING:
  from ..models.autor import Autor
  from ..models.dokument_hash_type_1_item import DokumentHashType1Item
  from ..models.touched_by_item import TouchedByItem
  from ..models.zusammenfassungstupel import Zusammenfassungstupel





T = TypeVar("T", bound="Dokument")



@_attrs_define
class Dokument:
    r""" A document. Could be a protocol, a Drucksache, a statement, ... For different objects, only certain properties are
    optional, which is a design flaw. \
    A Stellungnahme must contain `meinung`, a Gesetzentwurf contains `Vorwort`. \
    Since documents can become quite large, they are returned by the server as just their api_id in lists

        Example:
            {'api_id': 'a1b2c3d4-e5f6-7890-abcd-1234567890ab', 'typ': 'entwurf', 'titel': 'Entwurf eines Gesetzes zur
                Änderung des Bundeswahlgesetzes', 'kurztitel': 'Änderung des Bundeswahlgesetzes', 'vorwort': 'Mit dem
                vorliegenden Entwurf soll das Bundeswahlgesetz an die aktuellen Anforderungen angepasst werden.', 'volltext':
                'Der Bundestag hat mit Zustimmung des Bundesrates das folgende Gesetz beschlossen:\n\nArtikel 1\nÄnderung des
                Bundeswahlgesetzes\n\nDas Bundeswahlgesetz in der Fassung der Bekanntmachung vom 23. Juli 1993 (BGBl. I S. 1288,
                1594) wird wie folgt geändert:\n\n1. § 1 Absatz 1 wird wie folgt gefasst: [...]', 'zusammenfassung': 'Änderung
                des Bundeswahlgesetzes zur Anpassung an aktuelle Anforderungen.', 'zp_modifiziert': '2024-03-15T14:30:00+01:00',
                'zp_referenz': '2024-03-01T00:00:00+01:00', 'zp_erstellt': '2024-03-10T09:15:00+01:00', 'link':
                'https://dip.bundestag.de/dokument/12345', 'hash': 'a1b2c3d4e5f6g7h8i9j0', 'meinung': 4, 'schlagworte':
                ['wahlrecht', 'bundestagswahl', 'reform'], 'autoren': [{'person': 'Dr. Maria Schmidt', 'organisation':
                'Bundesministerium des Innern', 'fachgebiet': 'Wahlrecht'}], 'drucksnr': 'BT-Drs. 20/12345'}

        Attributes:
            typ (Doktyp): Type of a document
            titel (str): Offizieller Titel
            volltext (str): Full text of the document, possibly normalized
            zp_modifiziert (datetime.datetime): Protocol of the session on 7.3., created on 8.3. modified on 9.3. Example:
                2024-03-09T00:00:00+00:00.
            zp_referenz (datetime.datetime): Protocol of the session on 7.3., created on 8.3. modified on 9.3. Example:
                2024-03-07T00:00:00+00:00.
            link (str):
            hash_ (list[DokumentHashType1Item] | str):
            autoren (list[Autor]): List of authors of the document. Could be a person, organisation or a parliamentary body
            api_id (UUID | Unset): optional, here for future references. Is generated by the server. If you set it use UUID
                version 5 with your collector id as namespace
            touched_by (list[TouchedByItem] | Unset): list of scraper uuids / key database ids that have touched this object
            drucksnr (str | Unset):
            kurztitel (str | Unset): Griffigerer Titel für besseres Verständnis
            vorwort (str | Unset): Preabmle, synopsys or statement of intent
            zusammenfassung (list[Zusammenfassungstupel] | str | Unset):
            zp_erstellt (datetime.datetime | Unset): Protocol of the session on 7.3., created on 8.3. modified on 9.3.
                Example: 2024-03-08T00:00:00+00:00.
            subdoc_id (int | Unset): If a document contains more than one semantically closed document (x opinions in a
                collected file for example) this denotes the index of the sub-file in question. They can potentially share a
                hash.
            meinung (int | Unset): General opinion of the station in question. 1=very bad, 5=very good OR 1=rejection
                recommended, 2-4=accept in changed form, 5=acceptence recommended
            schlagworte (list[str] | Unset):
     """

    typ: Doktyp
    titel: str
    volltext: str
    zp_modifiziert: datetime.datetime
    zp_referenz: datetime.datetime
    link: str
    hash_: list[DokumentHashType1Item] | str
    autoren: list[Autor]
    api_id: UUID | Unset = UNSET
    touched_by: list[TouchedByItem] | Unset = UNSET
    drucksnr: str | Unset = UNSET
    kurztitel: str | Unset = UNSET
    vorwort: str | Unset = UNSET
    zusammenfassung: list[Zusammenfassungstupel] | str | Unset = UNSET
    zp_erstellt: datetime.datetime | Unset = UNSET
    subdoc_id: int | Unset = UNSET
    meinung: int | Unset = UNSET
    schlagworte: list[str] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.autor import Autor
        from ..models.dokument_hash_type_1_item import DokumentHashType1Item
        from ..models.touched_by_item import TouchedByItem
        from ..models.zusammenfassungstupel import Zusammenfassungstupel
        typ = self.typ.value

        titel = self.titel

        volltext = self.volltext

        zp_modifiziert = self.zp_modifiziert.isoformat()

        zp_referenz = self.zp_referenz.isoformat()

        link = self.link

        hash_: list[dict[str, Any]] | str
        if isinstance(self.hash_, list):
            hash_ = []
            for hash_type_1_item_data in self.hash_:
                hash_type_1_item = hash_type_1_item_data.to_dict()
                hash_.append(hash_type_1_item)


        else:
            hash_ = self.hash_

        autoren = []
        for autoren_item_data in self.autoren:
            autoren_item = autoren_item_data.to_dict()
            autoren.append(autoren_item)



        api_id: str | Unset = UNSET
        if not isinstance(self.api_id, Unset):
            api_id = str(self.api_id)

        touched_by: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.touched_by, Unset):
            touched_by = []
            for componentsschemastouched_by_item_data in self.touched_by:
                componentsschemastouched_by_item = componentsschemastouched_by_item_data.to_dict()
                touched_by.append(componentsschemastouched_by_item)



        drucksnr = self.drucksnr

        kurztitel = self.kurztitel

        vorwort = self.vorwort

        zusammenfassung: list[dict[str, Any]] | str | Unset
        if isinstance(self.zusammenfassung, Unset):
            zusammenfassung = UNSET
        elif isinstance(self.zusammenfassung, list):
            zusammenfassung = []
            for zusammenfassung_type_1_item_data in self.zusammenfassung:
                zusammenfassung_type_1_item = zusammenfassung_type_1_item_data.to_dict()
                zusammenfassung.append(zusammenfassung_type_1_item)


        else:
            zusammenfassung = self.zusammenfassung

        zp_erstellt: str | Unset = UNSET
        if not isinstance(self.zp_erstellt, Unset):
            zp_erstellt = self.zp_erstellt.isoformat()

        subdoc_id = self.subdoc_id

        meinung = self.meinung

        schlagworte: list[str] | Unset = UNSET
        if not isinstance(self.schlagworte, Unset):
            schlagworte = self.schlagworte




        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "typ": typ,
            "titel": titel,
            "volltext": volltext,
            "zp_modifiziert": zp_modifiziert,
            "zp_referenz": zp_referenz,
            "link": link,
            "hash": hash_,
            "autoren": autoren,
        })
        if api_id is not UNSET:
            field_dict["api_id"] = api_id
        if touched_by is not UNSET:
            field_dict["touched_by"] = touched_by
        if drucksnr is not UNSET:
            field_dict["drucksnr"] = drucksnr
        if kurztitel is not UNSET:
            field_dict["kurztitel"] = kurztitel
        if vorwort is not UNSET:
            field_dict["vorwort"] = vorwort
        if zusammenfassung is not UNSET:
            field_dict["zusammenfassung"] = zusammenfassung
        if zp_erstellt is not UNSET:
            field_dict["zp_erstellt"] = zp_erstellt
        if subdoc_id is not UNSET:
            field_dict["subdoc_id"] = subdoc_id
        if meinung is not UNSET:
            field_dict["meinung"] = meinung
        if schlagworte is not UNSET:
            field_dict["schlagworte"] = schlagworte

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.autor import Autor
        from ..models.dokument_hash_type_1_item import DokumentHashType1Item
        from ..models.touched_by_item import TouchedByItem
        from ..models.zusammenfassungstupel import Zusammenfassungstupel
        d = dict(src_dict)
        typ = Doktyp(d.pop("typ"))




        titel = d.pop("titel")

        volltext = d.pop("volltext")

        zp_modifiziert = isoparse(d.pop("zp_modifiziert"))




        zp_referenz = isoparse(d.pop("zp_referenz"))




        link = d.pop("link")

        def _parse_hash_(data: object) -> list[DokumentHashType1Item] | str:
            try:
                if not isinstance(data, list):
                    raise TypeError()
                hash_type_1 = []
                _hash_type_1 = data
                for hash_type_1_item_data in (_hash_type_1):
                    hash_type_1_item = DokumentHashType1Item.from_dict(hash_type_1_item_data)



                    hash_type_1.append(hash_type_1_item)

                return hash_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[DokumentHashType1Item] | str, data)

        hash_ = _parse_hash_(d.pop("hash"))


        autoren = []
        _autoren = d.pop("autoren")
        for autoren_item_data in (_autoren):
            autoren_item = Autor.from_dict(autoren_item_data)



            autoren.append(autoren_item)


        _api_id = d.pop("api_id", UNSET)
        api_id: UUID | Unset
        if isinstance(_api_id,  Unset):
            api_id = UNSET
        else:
            api_id = UUID(_api_id)




        _touched_by = d.pop("touched_by", UNSET)
        touched_by: list[TouchedByItem] | Unset = UNSET
        if _touched_by is not UNSET:
            touched_by = []
            for componentsschemastouched_by_item_data in _touched_by:
                componentsschemastouched_by_item = TouchedByItem.from_dict(componentsschemastouched_by_item_data)



                touched_by.append(componentsschemastouched_by_item)


        drucksnr = d.pop("drucksnr", UNSET)

        kurztitel = d.pop("kurztitel", UNSET)

        vorwort = d.pop("vorwort", UNSET)

        def _parse_zusammenfassung(data: object) -> list[Zusammenfassungstupel] | str | Unset:
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                zusammenfassung_type_1 = []
                _zusammenfassung_type_1 = data
                for zusammenfassung_type_1_item_data in (_zusammenfassung_type_1):
                    zusammenfassung_type_1_item = Zusammenfassungstupel.from_dict(zusammenfassung_type_1_item_data)



                    zusammenfassung_type_1.append(zusammenfassung_type_1_item)

                return zusammenfassung_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[Zusammenfassungstupel] | str | Unset, data)

        zusammenfassung = _parse_zusammenfassung(d.pop("zusammenfassung", UNSET))


        _zp_erstellt = d.pop("zp_erstellt", UNSET)
        zp_erstellt: datetime.datetime | Unset
        if isinstance(_zp_erstellt,  Unset):
            zp_erstellt = UNSET
        else:
            zp_erstellt = isoparse(_zp_erstellt)




        subdoc_id = d.pop("subdoc_id", UNSET)

        meinung = d.pop("meinung", UNSET)

        schlagworte = cast(list[str], d.pop("schlagworte", UNSET))


        dokument = cls(
            typ=typ,
            titel=titel,
            volltext=volltext,
            zp_modifiziert=zp_modifiziert,
            zp_referenz=zp_referenz,
            link=link,
            hash_=hash_,
            autoren=autoren,
            api_id=api_id,
            touched_by=touched_by,
            drucksnr=drucksnr,
            kurztitel=kurztitel,
            vorwort=vorwort,
            zusammenfassung=zusammenfassung,
            zp_erstellt=zp_erstellt,
            subdoc_id=subdoc_id,
            meinung=meinung,
            schlagworte=schlagworte,
        )


        dokument.additional_properties = d
        return dokument

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
