from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from dateutil.parser import isoparse
from typing import cast
from uuid import UUID
import datetime

if TYPE_CHECKING:
  from ..models.autor import Autor
  from ..models.dokument import Dokument
  from ..models.gremium import Gremium
  from ..models.top import Top
  from ..models.touched_by_item import TouchedByItem





T = TypeVar("T", bound="Sitzung")



@_attrs_define
class Sitzung:
    r""" plenary session, committee session or committee hearing. A session is a hearing if experts are invited.

        Example:
            {'api_id': 'b1a2c3d4-e5f6-7890-fedc-1234567890ab', 'titel': '143. Sitzung des Deutschen Bundestages', 'termin':
                '2024-05-20T09:00:00+02:00', 'gremium': {'parlament': 'BT', 'wahlperiode': 20, 'name': 'plenum'}, 'nummer': 143,
                'public': True, 'link': 'https://www.bundestag.de/sitzung/20240520', 'tops': [{'nummer': 1, 'titel': 'Eröffnung
                der Sitzung'}, {'nummer': 3, 'titel': 'Erste Beratung des von den Fraktionen SPD, BÜNDNIS 90/DIE GRÜNEN und FDP
                eingebrachten Entwurfs eines Gesetzes zur Änderung des Bundeswahlgesetzes', 'vorgang_id':
                ['123e4567-e89b-12d3-a456-426614174000'], 'dokumente': []}], 'dokumente': [{'api_id':
                'c1d2e3f4-a5b6-7890-cdef-1234567890gh', 'typ': 'tops', 'titel': 'Tagesordnung der 143. Sitzung des Deutschen
                Bundestages', 'volltext': 'TOP 1: Eröffnung der Sitzung\nTOP 2: Fragestunde\nTOP 3: Erste Beratung des
                Gesetzentwurfs zur Änderung des Bundeswahlgesetzes\n...', 'hash': 'a1b2c3d4e5f6g7h8i9j0', 'zp_modifiziert':
                '2024-05-15T14:30:00+02:00', 'zp_referenz': '2024-05-20T09:00:00+02:00', 'link':
                'https://www.bundestag.de/tagesordnung/20240520', 'autoren': [{'organisation': 'Deutscher Bundestag'}]}]}

        Attributes:
            termin (datetime.datetime):  Example: 2024-03-15T10:00:00+00:00.
            gremium (Gremium): A body in which decisions can be made: committees, plenary halls, cabinett, peoples, ...
            nummer (int):
            public (bool):
            tops (list[Top]):
            api_id (UUID | Unset): optional, here for future references. Is generated by the server. If you set it use UUID
                version 5 with your collector id as namespace
            touched_by (list[TouchedByItem] | Unset): list of scraper uuids / key database ids that have touched this object
            titel (str | Unset): Title if applicable
            link (str | Unset):
            dokumente (list[Dokument | str] | Unset): Announcements, agendas and changed/amended agendas
            experten (list[Autor] | Unset): List of invited experts. if this is not null or empty, a session is a hearing.
     """

    termin: datetime.datetime
    gremium: Gremium
    nummer: int
    public: bool
    tops: list[Top]
    api_id: UUID | Unset = UNSET
    touched_by: list[TouchedByItem] | Unset = UNSET
    titel: str | Unset = UNSET
    link: str | Unset = UNSET
    dokumente: list[Dokument | str] | Unset = UNSET
    experten: list[Autor] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.autor import Autor
        from ..models.dokument import Dokument
        from ..models.gremium import Gremium
        from ..models.top import Top
        from ..models.touched_by_item import TouchedByItem
        termin = self.termin.isoformat()

        gremium = self.gremium.to_dict()

        nummer = self.nummer

        public = self.public

        tops = []
        for tops_item_data in self.tops:
            tops_item = tops_item_data.to_dict()
            tops.append(tops_item)



        api_id: str | Unset = UNSET
        if not isinstance(self.api_id, Unset):
            api_id = str(self.api_id)

        touched_by: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.touched_by, Unset):
            touched_by = []
            for componentsschemastouched_by_item_data in self.touched_by:
                componentsschemastouched_by_item = componentsschemastouched_by_item_data.to_dict()
                touched_by.append(componentsschemastouched_by_item)



        titel = self.titel

        link = self.link

        dokumente: list[dict[str, Any] | str] | Unset = UNSET
        if not isinstance(self.dokumente, Unset):
            dokumente = []
            for dokumente_item_data in self.dokumente:
                dokumente_item: dict[str, Any] | str
                if isinstance(dokumente_item_data, Dokument):
                    dokumente_item = dokumente_item_data.to_dict()
                else:
                    dokumente_item = dokumente_item_data
                dokumente.append(dokumente_item)



        experten: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.experten, Unset):
            experten = []
            for experten_item_data in self.experten:
                experten_item = experten_item_data.to_dict()
                experten.append(experten_item)




        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "termin": termin,
            "gremium": gremium,
            "nummer": nummer,
            "public": public,
            "tops": tops,
        })
        if api_id is not UNSET:
            field_dict["api_id"] = api_id
        if touched_by is not UNSET:
            field_dict["touched_by"] = touched_by
        if titel is not UNSET:
            field_dict["titel"] = titel
        if link is not UNSET:
            field_dict["link"] = link
        if dokumente is not UNSET:
            field_dict["dokumente"] = dokumente
        if experten is not UNSET:
            field_dict["experten"] = experten

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.autor import Autor
        from ..models.dokument import Dokument
        from ..models.gremium import Gremium
        from ..models.top import Top
        from ..models.touched_by_item import TouchedByItem
        d = dict(src_dict)
        termin = isoparse(d.pop("termin"))




        gremium = Gremium.from_dict(d.pop("gremium"))




        nummer = d.pop("nummer")

        public = d.pop("public")

        tops = []
        _tops = d.pop("tops")
        for tops_item_data in (_tops):
            tops_item = Top.from_dict(tops_item_data)



            tops.append(tops_item)


        _api_id = d.pop("api_id", UNSET)
        api_id: UUID | Unset
        if isinstance(_api_id,  Unset):
            api_id = UNSET
        else:
            api_id = UUID(_api_id)




        _touched_by = d.pop("touched_by", UNSET)
        touched_by: list[TouchedByItem] | Unset = UNSET
        if _touched_by is not UNSET:
            touched_by = []
            for componentsschemastouched_by_item_data in _touched_by:
                componentsschemastouched_by_item = TouchedByItem.from_dict(componentsschemastouched_by_item_data)



                touched_by.append(componentsschemastouched_by_item)


        titel = d.pop("titel", UNSET)

        link = d.pop("link", UNSET)

        _dokumente = d.pop("dokumente", UNSET)
        dokumente: list[Dokument | str] | Unset = UNSET
        if _dokumente is not UNSET:
            dokumente = []
            for dokumente_item_data in _dokumente:
                def _parse_dokumente_item(data: object) -> Dokument | str:
                    try:
                        if not isinstance(data, dict):
                            raise TypeError()
                        dokumente_item_type_0 = Dokument.from_dict(data)



                        return dokumente_item_type_0
                    except (TypeError, ValueError, AttributeError, KeyError):
                        pass
                    return cast(Dokument | str, data)

                dokumente_item = _parse_dokumente_item(dokumente_item_data)

                dokumente.append(dokumente_item)


        _experten = d.pop("experten", UNSET)
        experten: list[Autor] | Unset = UNSET
        if _experten is not UNSET:
            experten = []
            for experten_item_data in _experten:
                experten_item = Autor.from_dict(experten_item_data)



                experten.append(experten_item)


        sitzung = cls(
            termin=termin,
            gremium=gremium,
            nummer=nummer,
            public=public,
            tops=tops,
            api_id=api_id,
            touched_by=touched_by,
            titel=titel,
            link=link,
            dokumente=dokumente,
            experten=experten,
        )


        sitzung.additional_properties = d
        return sitzung

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
