from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.stationstyp import Stationstyp
from ..types import UNSET, Unset
from dateutil.parser import isoparse
from typing import cast
from uuid import UUID
import datetime

if TYPE_CHECKING:
  from ..models.dokument import Dokument
  from ..models.gremium import Gremium
  from ..models.touched_by_item import TouchedByItem





T = TypeVar("T", bound="Station")



@_attrs_define
class Station:
    """ In many ways a station is the heart of this API. Every Vorgang consists of stations, which have only very few
    required fields. They represent meaningful steps that any Vorgang takes from start to finish. For further details,
    see the documentation.

        Example:
            {'api_id': 'f1e2d3c4-b5a6-7890-abcd-1234567890cd', 'titel': 'Erste Lesung im Bundestag', 'zp_start':
                '2024-04-15T10:00:00+02:00', 'zp_modifiziert': '2024-04-15T13:45:00+02:00', 'gremium': {'parlament': 'BT',
                'wahlperiode': 20, 'name': 'plenum'}, 'gremium_federf': False, 'link':
                'https://www.bundestag.de/dokumente/textarchiv/2024/erste-lesung-wahlrechtsreform', 'parlament': 'BT', 'typ':
                'parl-vollvlsgn', 'trojanergefahr': 2, 'schlagworte': ['wahlrecht', 'reform', 'bundestag'], 'dokumente': [],
                'additional_links': ['https://www.bundestag.de/mediathek/parlamentsfernsehen/aufzeichnungen/123456-123456']}

        Attributes:
            zp_start (datetime.datetime): Date of the first action within this station. i.e.: First session of a committee
                Example: 2024-01-01T00:00:00+00:00.
            gremium (Gremium): A body in which decisions can be made: committees, plenary halls, cabinett, peoples, ...
            typ (Stationstyp): Substantive legislative steps, that a Vorgang can pass on its way to a law or rejection or
                similar endings. The categorisation pre/postparl is to a degree arbitrary, these are just identifiers.
            dokumente (list[Dokument | str]):
            api_id (UUID | Unset): optional, here for future references. Is generated by the server. If you set it use UUID
                version 5 with your collector id as namespace
            touched_by (list[TouchedByItem] | Unset): list of scraper uuids / key database ids that have touched this object
            titel (str | Unset): optional title, if other data does not provide a proper description
            zp_modifiziert (datetime.datetime | Unset): Date of the last relevant action within this station. i.e.: last
                session of a committee Example: 2024-01-01T00:00:00+00:00.
            gremium_federf (bool | Unset): If the station if of type parl-ausschbsl, this field should be set if the
                committee is the main committee ('federführend')
            link (str | Unset): Link to a web page describing this NOT to a pdf document
            trojanergefahr (int | Unset): Currently unused. Always set to null
            schlagworte (list[str] | Unset):
            additional_links (list[str] | Unset):
            stellungnahmen (list[Dokument | str] | Unset):
     """

    zp_start: datetime.datetime
    gremium: Gremium
    typ: Stationstyp
    dokumente: list[Dokument | str]
    api_id: UUID | Unset = UNSET
    touched_by: list[TouchedByItem] | Unset = UNSET
    titel: str | Unset = UNSET
    zp_modifiziert: datetime.datetime | Unset = UNSET
    gremium_federf: bool | Unset = UNSET
    link: str | Unset = UNSET
    trojanergefahr: int | Unset = UNSET
    schlagworte: list[str] | Unset = UNSET
    additional_links: list[str] | Unset = UNSET
    stellungnahmen: list[Dokument | str] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.dokument import Dokument
        from ..models.gremium import Gremium
        from ..models.touched_by_item import TouchedByItem
        zp_start = self.zp_start.isoformat()

        gremium = self.gremium.to_dict()

        typ = self.typ.value

        dokumente = []
        for dokumente_item_data in self.dokumente:
            dokumente_item: dict[str, Any] | str
            if isinstance(dokumente_item_data, Dokument):
                dokumente_item = dokumente_item_data.to_dict()
            else:
                dokumente_item = dokumente_item_data
            dokumente.append(dokumente_item)



        api_id: str | Unset = UNSET
        if not isinstance(self.api_id, Unset):
            api_id = str(self.api_id)

        touched_by: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.touched_by, Unset):
            touched_by = []
            for componentsschemastouched_by_item_data in self.touched_by:
                componentsschemastouched_by_item = componentsschemastouched_by_item_data.to_dict()
                touched_by.append(componentsschemastouched_by_item)



        titel = self.titel

        zp_modifiziert: str | Unset = UNSET
        if not isinstance(self.zp_modifiziert, Unset):
            zp_modifiziert = self.zp_modifiziert.isoformat()

        gremium_federf = self.gremium_federf

        link = self.link

        trojanergefahr = self.trojanergefahr

        schlagworte: list[str] | Unset = UNSET
        if not isinstance(self.schlagworte, Unset):
            schlagworte = self.schlagworte



        additional_links: list[str] | Unset = UNSET
        if not isinstance(self.additional_links, Unset):
            additional_links = self.additional_links



        stellungnahmen: list[dict[str, Any] | str] | Unset = UNSET
        if not isinstance(self.stellungnahmen, Unset):
            stellungnahmen = []
            for stellungnahmen_item_data in self.stellungnahmen:
                stellungnahmen_item: dict[str, Any] | str
                if isinstance(stellungnahmen_item_data, Dokument):
                    stellungnahmen_item = stellungnahmen_item_data.to_dict()
                else:
                    stellungnahmen_item = stellungnahmen_item_data
                stellungnahmen.append(stellungnahmen_item)




        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "zp_start": zp_start,
            "gremium": gremium,
            "typ": typ,
            "dokumente": dokumente,
        })
        if api_id is not UNSET:
            field_dict["api_id"] = api_id
        if touched_by is not UNSET:
            field_dict["touched_by"] = touched_by
        if titel is not UNSET:
            field_dict["titel"] = titel
        if zp_modifiziert is not UNSET:
            field_dict["zp_modifiziert"] = zp_modifiziert
        if gremium_federf is not UNSET:
            field_dict["gremium_federf"] = gremium_federf
        if link is not UNSET:
            field_dict["link"] = link
        if trojanergefahr is not UNSET:
            field_dict["trojanergefahr"] = trojanergefahr
        if schlagworte is not UNSET:
            field_dict["schlagworte"] = schlagworte
        if additional_links is not UNSET:
            field_dict["additional_links"] = additional_links
        if stellungnahmen is not UNSET:
            field_dict["stellungnahmen"] = stellungnahmen

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.dokument import Dokument
        from ..models.gremium import Gremium
        from ..models.touched_by_item import TouchedByItem
        d = dict(src_dict)
        zp_start = isoparse(d.pop("zp_start"))




        gremium = Gremium.from_dict(d.pop("gremium"))




        typ = Stationstyp(d.pop("typ"))




        dokumente = []
        _dokumente = d.pop("dokumente")
        for dokumente_item_data in (_dokumente):
            def _parse_dokumente_item(data: object) -> Dokument | str:
                try:
                    if not isinstance(data, dict):
                        raise TypeError()
                    dokumente_item_type_0 = Dokument.from_dict(data)



                    return dokumente_item_type_0
                except (TypeError, ValueError, AttributeError, KeyError):
                    pass
                return cast(Dokument | str, data)

            dokumente_item = _parse_dokumente_item(dokumente_item_data)

            dokumente.append(dokumente_item)


        _api_id = d.pop("api_id", UNSET)
        api_id: UUID | Unset
        if isinstance(_api_id,  Unset):
            api_id = UNSET
        else:
            api_id = UUID(_api_id)




        _touched_by = d.pop("touched_by", UNSET)
        touched_by: list[TouchedByItem] | Unset = UNSET
        if _touched_by is not UNSET:
            touched_by = []
            for componentsschemastouched_by_item_data in _touched_by:
                componentsschemastouched_by_item = TouchedByItem.from_dict(componentsschemastouched_by_item_data)



                touched_by.append(componentsschemastouched_by_item)


        titel = d.pop("titel", UNSET)

        _zp_modifiziert = d.pop("zp_modifiziert", UNSET)
        zp_modifiziert: datetime.datetime | Unset
        if isinstance(_zp_modifiziert,  Unset):
            zp_modifiziert = UNSET
        else:
            zp_modifiziert = isoparse(_zp_modifiziert)




        gremium_federf = d.pop("gremium_federf", UNSET)

        link = d.pop("link", UNSET)

        trojanergefahr = d.pop("trojanergefahr", UNSET)

        schlagworte = cast(list[str], d.pop("schlagworte", UNSET))


        additional_links = cast(list[str], d.pop("additional_links", UNSET))


        _stellungnahmen = d.pop("stellungnahmen", UNSET)
        stellungnahmen: list[Dokument | str] | Unset = UNSET
        if _stellungnahmen is not UNSET:
            stellungnahmen = []
            for stellungnahmen_item_data in _stellungnahmen:
                def _parse_stellungnahmen_item(data: object) -> Dokument | str:
                    try:
                        if not isinstance(data, dict):
                            raise TypeError()
                        stellungnahmen_item_type_0 = Dokument.from_dict(data)



                        return stellungnahmen_item_type_0
                    except (TypeError, ValueError, AttributeError, KeyError):
                        pass
                    return cast(Dokument | str, data)

                stellungnahmen_item = _parse_stellungnahmen_item(stellungnahmen_item_data)

                stellungnahmen.append(stellungnahmen_item)


        station = cls(
            zp_start=zp_start,
            gremium=gremium,
            typ=typ,
            dokumente=dokumente,
            api_id=api_id,
            touched_by=touched_by,
            titel=titel,
            zp_modifiziert=zp_modifiziert,
            gremium_federf=gremium_federf,
            link=link,
            trojanergefahr=trojanergefahr,
            schlagworte=schlagworte,
            additional_links=additional_links,
            stellungnahmen=stellungnahmen,
        )


        station.additional_properties = d
        return station

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
