# generated by datamodel-codegen:
#   filename:  https://codeberg.org/PaZuFa/parlamentszusammenfasser/raw/branch/main/docs/specs/openapi.yml
#   timestamp: 2026-03-06T09:18:22+00:00

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel, conint


class KeyTag(RootModel[str]):
    root: str = Field(..., description="A uniquely identifying string that is generated from key data within the database")


class EnumerationNames(Enum):
    schlagworte = "schlagworte"
    stationstypen = "stationstypen"
    vorgangstypen = "vorgangstypen"
    parlamente = "parlamente"
    vgidtypen = "vgidtypen"
    dokumententypen = "dokumententypen"


class Scope(Enum):
    admin = "admin"
    collector = "collector"
    keyadder = "keyadder"


class CreateApiKey(BaseModel):
    scope: Scope
    expires_at: AwareDatetime | None = Field(None, description="The expiration date of the API Key", examples=["2024-12-31T23:59:59+00:00"])


class RotationResponse(BaseModel):
    new_api_key: str = Field(..., description="The newly created API key (shown only once)")
    rotation_complete_date: AwareDatetime = Field(..., description="Confirmed date when the old key will be invalidated")


class ApiKeyStatus(BaseModel):
    scope: Scope
    expires_at: AwareDatetime = Field(..., description="When this key will expire. If is_being_rotated is true, this is the date the rotation is complete.")
    is_being_rotated: bool = Field(..., description="Whether this key is currently in a transition process")


class Parlament(Enum):
    BT = "BT"
    BR = "BR"
    BV = "BV"
    EK = "EK"
    BB = "BB"
    BY = "BY"
    BE = "BE"
    HB = "HB"
    HH = "HH"
    HE = "HE"
    MV = "MV"
    NI = "NI"
    NW = "NW"
    RP = "RP"
    SL = "SL"
    SN = "SN"
    TH = "TH"
    SH = "SH"
    BW = "BW"
    ST = "ST"


class Vorgangstyp(Enum):
    gg_einspruch = "gg-einspruch"
    gg_zustimmung = "gg-zustimmung"
    gg_land_parl = "gg-land-parl"
    gg_land_volk = "gg-land-volk"
    bw_einsatz = "bw-einsatz"
    sonstig = "sonstig"


class Stationstyp(Enum):
    preparl_regent = "preparl-regent"
    preparl_eckpup = "preparl-eckpup"
    preparl_regbsl = "preparl-regbsl"
    preparl_vbegde = "preparl-vbegde"
    parl_initiativ = "parl-initiativ"
    parl_ausschber = "parl-ausschber"
    parl_vollvlsgn = "parl-vollvlsgn"
    parl_akzeptanz = "parl-akzeptanz"
    parl_ablehnung = "parl-ablehnung"
    parl_zurueckgz = "parl-zurueckgz"
    parl_ggentwurf = "parl-ggentwurf"
    postparl_vesja = "postparl-vesja"
    postparl_vesne = "postparl-vesne"
    postparl_gsblt = "postparl-gsblt"
    postparl_kraft = "postparl-kraft"
    sonstig = "sonstig"


class VgIdentTyp(RootModel[str]):
    root: str = Field(
        ...,
        description="Typ von Identifikatoren für einen gesamten Vorgang. Offen für was auch immer ein Parlament benutzt um einen Vorgang zu identifizieren. Aktuell in der Datenbank: initdrucks, vorgnr, api-id, sonstig bitte keine neue Abkürzung für denselben Typ erfinden",
        examples=["initdrucks"],
    )


class Doktyp(Enum):
    preparl_entwurf = "preparl-entwurf"
    entwurf = "entwurf"
    antrag = "antrag"
    anfrage = "anfrage"
    antwort = "antwort"
    mitteilung = "mitteilung"
    beschlussempf = "beschlussempf"
    stellungnahme = "stellungnahme"
    gutachten = "gutachten"
    redeprotokoll = "redeprotokoll"
    tops = "tops"
    tops_aend = "tops-aend"
    tops_ergz = "tops-ergz"
    sonstig = "sonstig"


class Gremium(BaseModel):
    parlament: Parlament
    wahlperiode: conint(ge=0)
    link: AnyUrl | None = None
    name: str = Field(
        ...,
        description="Name des betreffenden Gremiums. 'plenum', 'regierung', 'volk' sind reservierte namen",
        examples=["Ausschuss für Inneres und Gemüseauflauf"],
    )


class TouchedByItem(BaseModel):
    scraper_id: UUID | None = Field(None, description="uuid of the scraper that touched this object")
    key: str | None = Field(None, description="Key hash of the scraper that touched the object")


class TouchedBy(RootModel[list[TouchedByItem]]):
    root: list[TouchedByItem] = Field(..., description="list of scraper uuids / key database ids that have touched this object")


class VgIdent(BaseModel):
    id: str = Field(..., examples=["123e4567-e"])
    typ: VgIdentTyp


class Autor(BaseModel):
    person: str | None = None
    organisation: str
    fachgebiet: str | None = None
    lobbyregister: AnyUrl | None = None


class Dokument(BaseModel):
    api_id: UUID | None = Field(None, description="optional, here for future references. Is generated by the server.")
    touched_by: TouchedBy | None = None
    drucksnr: str | None = None
    typ: Doktyp
    titel: str = Field(..., description="Offizieller Titel")
    kurztitel: str | None = Field(None, description="Griffigerer Titel für besseres Verständnis")
    vorwort: str | None = Field(None, description="Präambel, Vorwort oder Intentionsbeschreibung. Wird für Ähnlichkeitsanalysen von Gesetzestexten genutzt")
    volltext: str = Field(..., description="Volltext des Dokuments")
    zusammenfassung: str | None = None
    zp_modifiziert: AwareDatetime = Field(
        ..., description="Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert am 9.3.", examples=["2024-03-09T00:00:00+00:00"]
    )
    zp_referenz: AwareDatetime = Field(
        ..., description="Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert am 9.3.", examples=["2024-03-07T00:00:00+00:00"]
    )
    zp_erstellt: AwareDatetime | None = Field(
        None, description="Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert am 9.3.", examples=["2024-03-08T00:00:00+00:00"]
    )
    link: AnyUrl
    hash: str
    meinung: conint(ge=1, le=5) | None = Field(
        None,
        description="Meinungsbild des Dokuments bei Stln / Beschlempf: 1=schlecht, 5=gut bzw. 1=ablehnung empf.,2-4=zust in geänderter Fassung, 5=zustimmung empf.",
    )
    schlagworte: list[str] | None = None
    autoren: list[Autor] = Field(..., description="Liste von Autoren des Dokuments. Kann z.B. eine Person, eine Organisation oder ein Gremium sein.")


class Station(BaseModel):
    api_id: UUID | None = Field(None, description="optional, here for future references. Is generated by the server.")
    touched_by: TouchedBy | None = None
    titel: str | None = Field(None, description="Optionaler Titel, falls die restlichen Daten keinen hinreichenden Rückschluss zulassen")
    zp_start: AwareDatetime = Field(
        ...,
        description="Datum an dem die erste Aktion dieser Station erstellt wurde, z.B. Erstes Sitzungsdatum des Ausschusses",
        examples=["2024-01-01T00:00:00+00:00"],
    )
    zp_modifiziert: AwareDatetime | None = Field(
        None,
        description="Letztes relevantes Datum an dem die Station angefasst wurde z.B.: letzte sitzung oder nächste geplante sitzung",
        examples=["2024-01-01T00:00:00+00:00"],
    )
    gremium: Gremium
    gremium_federf: bool | None = Field(None, description="Ist die Station eine Ausschussberatung gibt dieses Feld an ob es im Federführenden Ausschuss ist")
    link: AnyUrl | None = Field(None, description="Link zu einer Übersichtsseite zu dieser Station. _NICHT_ zu einem Dokument (PDF)")
    typ: Stationstyp
    trojanergefahr: conint(ge=1, le=10) | None = Field(None, description="Zahl im Intervall [1;10], die die Gefahr einer Schummelei angeben")
    schlagworte: list[str] | None = None
    dokumente: list[Dokument | str]
    additional_links: list[AnyUrl] | None = None
    stellungnahmen: list[Dokument | str] | None = None


class Lobbyregeintrag(BaseModel):
    organisation: Autor
    interne_id: str = Field(..., description="Interne ID des Lobbyregisters, notwendig für die bildung von Links")
    intention: str = Field(..., description="Lobbyregistereintrag zu dem  Was und Warum man auf den Vorgang Einfluss nehmen will")
    link: AnyUrl = Field(..., description="Direktlink zum Lobbyregistereintrag")
    betroffene_drucksachen: list[str] = Field(
        ..., description="Stringarray mit betroffenen Drucksachennummern. Wird in der Datenbank _nicht_ integriert und nur flach aufgelegt"
    )


class Vorgang(BaseModel):
    api_id: UUID = Field(..., examples=["123e4567-e89b-12d3-a456-426614174000"])
    touched_by: TouchedBy | None = None
    titel: str
    kurztitel: str | None = None
    wahlperiode: conint(ge=0) = Field(..., description="Nummer der Wahlperiode, in der der Vorgang stattfindet")
    verfassungsaendernd: bool
    typ: Vorgangstyp
    ids: list[VgIdent] | None = None
    links: list[AnyUrl] | None = None
    initiatoren: list[Autor] = Field(
        ...,
        description="Liste von Personen oder Organisationen, die den Vorgang initiiert haben. Kann z.B. eine Person, eine Organisation oder ein Gremium sein.",
    )
    stationen: list[Station]
    lobbyregister: list[Lobbyregeintrag] | None = None


class Top(BaseModel):
    nummer: conint(ge=0) = Field(..., description="Nummer des TOPs in einer Sitzung")
    titel: str
    vorgang_id: list[UUID] | None = Field(
        None, description="Die Nummer assoziierter Vorgänge. Wird beim Upload ignoriert, aber beim Download mitgegeben zusammen mit den konkreten Drucksachen"
    )
    dokumente: list[Dokument | str] | None = Field(None, description="Die Dokumente, die in diesem TOP besprochen werden sollen")


class Sitzung(BaseModel):
    api_id: UUID | None = Field(None, description="optional, here for future references. Is generated by the server.")
    touched_by: TouchedBy | None = None
    titel: str | None = Field(None, description="Titel wenn anwendbar. In den Ländern sind Themenüberschriften für AS üblich")
    termin: AwareDatetime = Field(..., examples=["2024-03-15T10:00:00+00:00"])
    gremium: Gremium
    nummer: conint(ge=0)
    public: bool
    link: AnyUrl | None = None
    tops: list[Top]
    dokumente: list[Dokument | str] | None = Field(None, description="Ankündigungen, TOPs und TOP änderungen bzw. Ergänzungen")
    experten: list[Autor] | None = Field(None, description="Optional: Liste von geladenen Experten. (macht aus der Sitzung eine Anhörung)")
