when:
  - event: [pull_request]

labels:
  pazufa_scope: generic

variables: # https://woodpecker-ci.org/docs/usage/advanced-usage#anchors--aliases
  - &python_image 'ghcr.io/astral-sh/uv:python3.12-bookworm-slim'

steps:
  - name: setup
    image: *python_image
    commands:
      - uv sync --frozen

  - name: lint
    image: *python_image
    commands:
      - uv run ruff check .

  - name: format
    image: *python_image
    commands:
      - uv run ruff format --check .

  - name: type-check
    image: *python_image
    commands:
      - uv run ty check .

  - name: test
    image: *python_image
    commands:
      - uv run pytest
