when:
  - event: pull_request

labels:
  pazufa_scope: generic

variables:
  - &python_image 'ghcr.io/astral-sh/uv:python3.12-trixie-slim'

steps:
  setup:
    image: *python_image
    commands:
      - uv sync --frozen

  lint:
    image: *python_image
    commands:
      - uv run ruff check .

  format:
    image: *python_image
    commands:
      - uv run ruff format --check .

  type-check:
    image: *python_image
    commands:
      - uv run ty check .

  test:
    image: *python_image
    commands:
      - uv run pytest
